language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - travis_retry composer self-update
  - travis_wait composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit
